### PR TITLE
Added logic for hardware interfaces

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>

Related with this issue

https://github.com/ros-controls/gz_ros2_control/issues/62

### CODE REVIEW

**Review by destogl — APPROVED** [review]
I think this is good for now. Maybe at some point we have to add also hardware lifecycle in the simulation.

**Comment by rcywongaa** [comment]
Should this be backported to the humble branch?

**Comment by destogl** [comment]
@ahcorde we should also push this to master

**Comment by destogl** [comment]
Oh we should backport a lot to humble. Actually we should proabably reset it to master for now. It should work.

**Pull request merged**
