### PR TITLE
Fix #259 - `ParameterAlreadyDeclaredException` for parameter `position_proportional_gain`

### LINKED ISSUE #259: ParameterAlreadyDeclaredException for parameter `position_proportional_gain`
Since [PR 248](https://github.com/ros-controls/gz_ros2_control/pull/248) I get an **rclcpp::exceptions::ParameterAlreadyDeclaredException** for the parameter `position_proportional_gain`:

grafik

This due to my URDF setup, where I have macros, in which I have defined ros2_control tags that contain the line `<plugin>ign_ros2_control/IgnitionSystem</plugin>`. When the macro is called the first time, everything is fine, when it is called the second time, I get the ParameterAlreadyDeclaredException.
My macro looks like this:
```
<xacro:macro name="rubber_wheel_transmission" params="prefix ">
    <ros2_control name="${prefix}_wheel_joint_ros2_control" type="system">
        <hardware>
            <plugin>ign_ros2_control/IgnitionSystem</plugin>
	</hardware> 
	<joint name="${prefix}_wheel_joint">
	    <command_interface name="velocity">
	        <param name="min">-1</param>
		<param name="max">1</param>
	    </command_interface>
	    <state_interface name="position"/>
            <state_interface name="velocity"/>
	</joint>
    </ros2_control>
</xacro:macro>
```

My questions now are:
1. Do I use the `<plugin>ign_ros2_control/IgnitionSystem</plugin>` tag wrongly, so should it only be once in my complete URDF description?
2. How do I set the parameter `position_proportional_gain`? In my understanding it should be possible to set the parameter independently for every joint, so something like
```
<hardware>
    <plugin>ign_ros2_control/IgnitionSystem</plugin>
    <param name="position_proportional_gain">0.5</param>
</hardware>
```

### PR DESCRIPTION
**Pull request by roncapat**
Fixes #259. 

@TipluJacob could you try check out this branch or apply this small patch on your setup and see if it works again?

### CODE REVIEW

**Comment by TipluJacob** [comment]
I am sorry, my setup currently only works with **humble** and when I try to build your branch with my humble setup it fails, which is probably no surprise:

grafik

**Comment by roncapat** [comment]
can you apply manually https://github.com/ros-controls/gz_ros2_control/pull/261/files?

**Comment by TipluJacob** [comment]
Yes, I could manually apply those changes and it works now. Although for the second joint it now reports that the `position_proportional_gain` has been set to 0.
It just does not feel like a clean solution, but for now it seems alright.

grafik

**Comment by roncapat** [comment]
I agree, this should not happen. I will investigate.

**Comment by roncapat** [comment]
@TipluJacob friendly ping, I updated the patch. Could you check again?

**Comment by TipluJacob** [comment]
Yea, this looks better now:
grafik

**Comment by roncapat** [comment]
Ok, at least now, with respect to previous baseline, there is:
- (retention of the) possibility to load multiple systems
- possibility to change the (otherwise defaulted) gain value globally.

Note: even before, it was a value globally defaulted.

**Review by destogl — APPROVED** [review]
I have applied this to humble (cherry-picking) and can confirm that it is working!

Thanks!

**Comment by roncapat** [comment]
Thank you!

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport humble iron

**Pull request merged**
