### PR TITLE
Use Gazebo ROS vendor packages

### PR DESCRIPTION
**Pull request by azeey**
Changes:
* Update all package.xml and CMakeLists files to use Gazebo vendor packages that are now available in rolling and the upcoming jazzy.
* Update Github Actions to run on Ubuntu Noble
* Clean up code where both ign and gz headers were supported.

### CODE REVIEW

**Comment by azeey** [comment]
> ros-rolling-ros-gz-sim is still not [released](https://build.ros2.org/search/?q=ros_gz_sim), or is there an other issue with the config?

Yeah, I think that's the only issue.

**Comment by azeey** [comment]
ros-rolling-ros-gz-sim is not available on ros2-testing.

**Review by ahcorde — CHANGES_REQUESTED** [review]
There are some errors on CI, do you mind to take a look ?

**Comment by azeey** [comment]
Has there been a release of `ros2_control` into rolling since https://github.com/ros-controls/ros2_control/pull/1256? That seems to be the issue here.

**Comment by christophfroehlich** [comment]
> Has there been a release of `ros2_control` into rolling since [ros-controls/ros2_control#1256](https://github.com/ros-controls/ros2_control/pull/1256)? That seems to be the issue here.

yes, today ;) https://github.com/ros/rosdistro/pull/41012

**Review by fmauch — COMMENTED** [review]
That change looks like it would also need a README update.

Apart from that I tested building this locally on ubuntu noble with the testing repo enabled and did a quick test using ur_simulation_gz against this.

**Comment by azeey** [comment]
> That change looks like it would also need a README update.
> 

I've updated the README to add Jazzy. Let me know if there's a specific change you had in mind.

**Comment by fmauch** [comment]
> > That change looks like it would also need a README update.
> 
> I've updated the README to add Jazzy. Let me know if there's a specific change you had in mind.

Yes, these are the changes that I had in mind, thank you for updating this. Currently, I find it a bit troublesome to find out which "rolling" means "rolling an noble" and which means "rolling on jammy, we haven't updated our docs, yet". The proposed changes make that clear in my opinion.

**Comment by azeey** [comment]
I've fixed flake8 failures in https://github.com/ros-controls/gz_ros2_control/pull/277/commits/affdb76c3e72e0f82469679e67cb658b3e58110f. CI should hopefully be green now. Please take a look.

**Review by ahcorde — APPROVED** [review]

**Comment by christophfroehlich** [comment]
@azeey will the vendor packages be released for distros < Jazzy as well? Up to this PR we were able to compile the rolling version of the ros2_control stack on iron and humble, but now this obviously fails https://github.com/ros-controls/ros2_control_ci/actions/runs/8994845511

**Comment by azeey** [comment]
We're currently not planning to release the vendor packages for earlier versions. If there is a lot of interest, we might consider releasing them, but they would require more work, so I don't think it will be anytime soon.

**Comment by azeey** [comment]
>  Up to this PR we were able to compile the rolling version of the ros2_control stack on iron and humble

I wasn't aware of this. I don't see a clean way to accomplish this with the vendor packages. In general, I was under the impression that [best practice](https://docs.ros.org/en/rolling/The-ROS2-Project/Contributing/Developer-Guide.html#branches) was to have a branch for each ROS version and backport changes if necessary. This is at least what the packages in the ROS core do. So I assumed `master` would only support Jazzy when it came out.

**Comment by christophfroehlich** [comment]
> > Up to this PR we were able to compile the rolling version of the ros2_control stack on iron and humble
> 
> I wasn't aware of this. I don't see a clean way to accomplish this with the vendor packages. In general, I was under the impression that [best practice](https://docs.ros.org/en/rolling/The-ROS2-Project/Contributing/Developer-Guide.html#branches) was to have a branch for each ROS version and backport changes if necessary. This is at least what the packages in the ROS core do. So I assumed `master` would only support Jazzy when it came out.

You are right and in principle we use this scheme. But we wanted to have the opportunity to use new features in the LTS distros (which are the only ones used by the industry) without the extra work on backporting them with proper deprecations/without any ABI/API breaks. This is why we added these CI checks to see if we break our code to be compilable on the older LTS distros. This is now the case with this PR (which is fine for rolling/jazzy and makes totally sense). 

I tried to just import all the vendor packages but it fails on dependencies not available on jammy https://github.com/ros-controls/ros2_control_ci/pull/77 What would be necessary to add the vendor package at least for the humble LTS? (we can move the discussion to the ros2_control_ci PR)

**Pull request merged**
