### PR TITLE
Mimic Joint Improvement

### PR DESCRIPTION
**Pull request by livanov93**
After ros-controls/gz_ros2_control#33 has been merged I stumbled upon small errors and spaces for improvement.
PR info:
- moving from `JointVelocityCmd` to `JointVelocityReset` because there was an error in handling joint limits and recovery from hitting them (more information can be found [here](https://github.com/gazebosim/gz-sim/issues/1684) )
- mimic joint control method is now handled in `perform_command_mode_switch` which is called upon any controller switch.

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
originally I was using `JointPositionReset` and `JointVelocityReset` bit it's a bad idea, these components are not design to be used like this. I have my concern about following up with this idea. we should fix the issue in `gz-sim`

**Comment by destogl** [comment]
> originally I was using `JointPositionReset` and `JointVelocityReset` bit it's a bad idea, these components are not design to be used like this. I have my concern about following up with this idea. we should fix the issue in `gz-sim`

Do you have any idea what is causing the issue?

**Comment by livanov93** [comment]
@ahcorde I opened an [issue](https://github.com/gazebosim/gz-sim/issues/1684) in `gz-sim`. Could we collaborate on fixing this?

**Comment by ahcorde** [comment]
> @ahcorde I opened an [issue](https://github.com/gazebosim/gz-sim/issues/1684) in `gz-sim`. Could we collaborate on fixing this?

Response here https://github.com/ros-controls/gz_ros2_control/pull/67#issuecomment-1268865166

**Comment by MarqRazz** [comment]
I'm building a mobile manipulator and this PR fixes the `GripperActionController` on the Robotiq but my mobile base `DiffDriveController` looses the ability to turn if I'm on this branch in Ignition Gazebo. It can still move forward/reverse but not rotate. Switching between this branch and `humble` I can re-enable rotating but loose the gripper.

**Comment by moriarty** [comment]
> > originally I was using `JointPositionReset` and `JointVelocityReset` bit it's a bad idea, these components are not design to be used like this. I have my concern about following up with this idea. we should fix the issue in `gz-sim`
> 
> Do you have any idea what is causing the issue?

> > @ahcorde I opened an [issue](https://github.com/gazebosim/gz-sim/issues/1684) in `gz-sim`. Could we collaborate on fixing this?
> 
> Response here [#67 (comment)](https://github.com/ros-controls/gz_ros2_control/pull/67#issuecomment-1268865166)


I just ran into this issue myself: https://github.com/PickNikRobotics/ros2_robotiq_gripper/issues/7
and applying the patch from this PR did fix it: https://github.com/ros-controls/gz_ros2_control/pull/86.patch
But the patch doesn't apply cleanly on Rolling, it did on Humble.

@ahcorde & @azeey what's the best way forward? You mentioned we should fix the issue in `gz-sim`
There haven't been any comments on the issue filed https://github.com/gazebosim/gz-sim/issues/1684
Do you have any suggestions or ideas that we can help with?

**Pull request closed without merging**
