### PR TITLE
propagate gazebo remapping and other arguments to the controller node

### PR DESCRIPTION
**Pull request by saikishor**
Changes to have remapping. Similar approach to: https://github.com/ros-controls/ros2_control/pull/1712

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
@saikishor should we backport this to other distros?

**Comment by saikishor** [comment]
> @saikishor should we backport this to other distros?

Yes, It would be needed for Jazzy

**Comment by saikishor** [comment]
> @saikishor should we backport this to other distros?

Yes, It would be needed for Jazzy

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport jazzy

**Pull request merged**
